### ISSUE TITLE
bug: UUID not defined

### ISSUE THREAD

**Issue by miili** [mkdocstrings/griffe-pydantic#10]
### Description of the bug
Model cannot be serialized for mkdocs

### To Reproduce
Complex call stack. The traceback might be enough for a start.

### Full traceback

<details><summary>
ERROR   -  Error reading page 'components/octree.md': `DetectionRequest` is not fully defined; you should define `UUID`, then call `DetectionRequest.model_rebuild()`.

</summary>

```pytb
ERROR   -  Error reading page 'components/octree.md': `DetectionRequest` is not fully defined; you should define `UUID`, then call `DetectionRequest.model_rebuild()`.
           For further information visit https://errors.pydantic.dev/2.9/u/class-not-fully-defined
Traceback (most recent call last):
  File "/home/marius/Development/qseek/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.render(config, files)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocs/structure/pages.py", line 285, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/markdown/core.py", line 357, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/markdown/blockparser.py", line 117, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/markdown/blockparser.py", line 136, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/markdown/blockparser.py", line 158, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocstrings/extension.py", line 130, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocstrings/extension.py", line 218, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/mkdocstrings_handlers/python/handler.py", line 330, in collect
    loader.load(
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/_griffe/loader.py", line 186, in load
    return self._post_load(top_module, obj_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/_griffe/loader.py", line 212, in _post_load
    self.extensions.call("on_package_loaded", pkg=module, loader=self)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/_griffe/extensions/base.py", line 313, in call
    getattr(extension, event)(**kwargs)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/griffe_pydantic/extension.py", line 42, in on_package_loaded
    static.process_module(pkg, processed=self.processed, schema=self.schema)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/griffe_pydantic/static.py", line 168, in process_module
    process_module(submodule, processed=processed, schema=schema)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/griffe_pydantic/static.py", line 165, in process_module
    process_class(cls, processed=processed, schema=schema)
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/griffe_pydantic/static.py", line 142, in process_class
    cls.extra[common.self_namespace]["schema"] = common.json_schema(true_class)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/griffe_pydantic/common.py", line 50, in json_schema
    return json.dumps(model.model_json_schema(), indent=2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/pydantic/main.py", line 476, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/pydantic/json_schema.py", line 2274, in model_json_schema
    cls.__pydantic_core_schema__.rebuild()
  File "/home/marius/Development/qseek/.venv/lib/python3.12/site-packages/pydantic/_internal/_mock_val_ser.py", line 66, in rebuild
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `DetectionRequest` is not fully defined; you should define `UUID`, then call `DetectionRequest.model_rebuild()`.

For further information visit https://errors.pydantic.dev/2.9/u/class-not-fully-defined
```

</details>

### Environment information

- __System__: Linux-6.10.11-amd64-x86_64-with-glibc2.40
- __Python__: cpython 3.12.6 (/home/marius/Development/qseek/.venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `griffe-pydantic` v1.0.0

**Comment by pawamoy** [comment]
Hi @miili, thanks for the report.

Have you tried calling `DetectionRequest.model_rebuild()`, as suggested in the error message? Or `UUID.model_rebuild()`? I'm not sure which one is the problematic class.

**Comment by miili** [comment]
Me stupid. A stray module caused this behavior.

**Comment by pawamoy** [comment]
No worries, thanks for coming back and closing 🙂
